# Generated by Django 5.1.6 on 2025-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0002_alter_receitas_table_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
